// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./views/404.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    File: typeof import('./views/yunpan/file.vue')['default']
    FormDialog: typeof import('./components/common/form-dialog/index.vue')['default']
    Home: typeof import('./views/home.vue')['default']
    Login: typeof import('./views/login.vue')['default']
    MainLayout: typeof import('./components/ui/MainLayout.vue')['default']
    NavMenuItem: typeof import('./components/ui/NavMenuItem.vue')['default']
    NavMenus: typeof import('./components/ui/NavMenus.vue')['default']
    Permission: typeof import('./views/backstage-management/permission/index.vue')['default']
    PermissionForm: typeof import('./views/backstage-management/permission/permission-form.vue')['default']
    Role: typeof import('./views/backstage-management/role/index.vue')['default']
    RoleForm: typeof import('./views/backstage-management/role/role-form.vue')['default']
    RolePermission: typeof import('./views/backstage-management/role-permission/index.vue')['default']
    Router: typeof import('./views/backstage-management/router/index.vue')['default']
    RouterForm: typeof import('./views/backstage-management/router/router-form.vue')['default']
    Tabs: typeof import('./components/ui/Tabs.vue')['default']
    Undefined: typeof import('./views/index.vue')['default']
    Upload: typeof import('./components/common/upload/index.vue')['default']
    UserForm: typeof import('./views/backstage-management/users/user-form.vue')['default']
    UserRole: typeof import('./views/backstage-management/user-role/index.vue')['default']
    Users: typeof import('./views/backstage-management/users/index.vue')['default']
  }
}

export { }
